var mymap = new Map()
mymap.set(1, "Vaishnavi")
mymap.set(2, "Shravani")
mymap.set(3, "Shewta")
mymap.set(4, "Arti")
console.log(mymap)
for(let key of mymap.keys())
console.log('key is', key)
for (let value of mymap.values())
console.log('value is',value)
console.log(mymap.get(4))
for (let[key,value] of mymap)
    console.log('key is',key, 'and value is', value)